version: '3.8'

services:
  github_app:
    build: .
    ports:
      - "5200:5200"
    environment:
      DB_HOST: "postgres_db"
      DB_NAME: "githubmonitor"
      DB_TEST_NAME: "githubmonitortest"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      DB_PORT: "5432"
      REDIS_URL: "redis:6379"
      GITHUB_API_BASE_URL: "https://api.github.com"
      GITHUB_REPO_FULL_NAME: "lakeside763/github-monitor"
      GITHUB_ACCOUNT_OWNER: "lakeside763"
      GITHUB_REPO_NAME: "github-monitor"
      MONITORING_INTERVAL: "120"
      FETCH_LIMIT: "5"
    depends_on:
      - postgres_db
      - redis

  postgres_db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: githubmonitor
    ports:
      - "5435:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.10-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_db_data:
  redis_data:
